@hostname = http://localhost:5000/api

### view order information

GET {{hostname}}/order/order-info
Content-Type: application/json

{
    "order_id": "93ebc2e9-7b45-440f-b87d-43c7c8477267"
}

### create new order

POST {{hostname}}/order/create-new-order
Content-Type: application/json

{
    "payment_method": "cash",
    "order": {
        "user_id": "0f1792a6-aa78-41ed-9e65-f761b5808089",
        "invite_type": "INVTYPE",
        "material": "material",
        "event_date": "2022-10-13 1:01:01",
        "motif": "motif",
        "invite_title": "material",
        "font_style": "italics",
        "content_link": "material",
        "num_of_invites": 20,
        "peg_link": "pinterest.com",
        "date_ordered": "2022-09-20 15:30:30",
        "order_deadline": "2022-09-20 1:01:01",
        "claim_type": "delivery",
        "order_status": "pending"

    },
//pass an array of objects for the order details
"items_array": [
    {"item_id": "m1", "item_name":"name", "price":20, "type": "orange", "size": "5.75 x 6.75", "quantity": 3},
    {"item_id": "e1", "item_name":"name", "price":20, "type": "red", "size": "6 x 7"},
    {"item_id": "e3", "item_name":"name", "price":20, "type": "euhue"},
    {"item_id": "co2", "item_name":"name", "price":20, "type": "covertype"},
    {"item_id": "d1", "item_name":"name", "price":20, "type": "leaves", "color": "blue"}
    ]

}

### update order status

PUT {{hostname}}/order/update-status
Content-Type: application/json

{
    "order_id": "da5060cc-7d09-4848-8270-df519a1e58f4",
    "order_status": "confimed"
}

### update order

PUT {{hostname}}/order/update-order
Content-Type: application/json

{
    "order": {
        "order_id": "93ebc2e9-7b45-440f-b87d-43c7c8477267",
        "font_style": "COMIC SANS",
        "material": "iron"
    }
}

### update order details

PUT {{hostname}}/order/update-order-details
Content-Type: application/json

{
    "order_id": "93ebc2e9-7b45-440f-b87d-43c7c8477267",
    "order_details": [
    {"item_id": "m1", "type": "blue","color": "blue", "size": "5.75 x 6.75", "quantity": 3},
    {"item_id": "e1", "type": "blue", "size": "6 x 7"},
    {"item_id": "e3", "type": "blue"},
    {"item_id": "co2", "type": "bluecovertype"},
    {"item_id": "d1", "type": "blueleaves", "color": "blue"},
    {"item_id": "t2", "type": "blueblue", "color": "blue"}

    ]
}

### cancel order

PUT {{hostname}}/order/cancel-order
Content-Type: application/json

{
    "order_id": "bcb5b2ce-b3e7-4642-aac2-c6e93857b81a",
    "order_status": "canceled"
}

### view order history

GET {{hostname}}/order/order-history

### my orders for customer

GET {{hostname}}/order/my-orders
Content-Type: application/json

{
    "user_id": "4d1e5e52-0979-4a2c-9e79-8b2b7b79d860"
}

### view current orders for staff

GET {{hostname}}/order/current-orders

### new doc entry

POST {{hostname}}/order/new-log-entry
Content-Type: application/json

{
    "order_id": "7a32d018-75b8-4f13-850a-f29cbdb04b92",
    "date": "2022-09-08 01:01:01",
    "description": "layout changed 1st time"
}

### view list of doc entry

GET {{hostname}}/order/order-log-list
Content-Type: application/json

{
    "order_id": "93ebc2e9-7b45-440f-b87d-43c7c8477267"
}


### upload image for invite draft

POST {{hostname}}/order/update-invite-draft
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="image"; filenamSe="zpermit.png"
Content-Type: image/png

< ./zpermit.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--


