@hostname = http://localhost:5000/api

### test route
GET {{hostname}}/customer/get-test

### create new customer

POST {{hostname}}/customer/sign-up
Content-Type: application/json

{
    "full_name": "Macaroni N. Cheese",
    "phone_number": "0101010",
    "email": "issapa@gmail.com",
    "password": "testing",
    "fb_account": "MNC.WAP",
    "full_address": "somethnsomethn"
}


### customer log in

POST {{hostname}}/customer/log-in
Content-Type: application/json

{
    "email": "thassawa@gmail.com",
    "password": "testing"
}

### create new order

POST {{hostname}}/order/order-form
Content-Type: application/json

{
    "order_details": {
        "invite_type": "invite type",
        "event_date": "2022-09-01",
        "motif": "motif",
        "font_style": "font style",
        "quantity": "quantity",
        "inner_type": "inner type",
        "outer_type": "outter type",
        "envelope_type": "envelope type",
        "inner_size": "inner size",
        "outer_size": "outter size",
        "envelope_size": "envelope size"
    },
    "additional_details": {
        "emboss": "true",
        "dry_emboss": "true",
        "plain_print": "true",
        "foil_print": "true",
        "monetary_gift": "true",
        "RSVP": "false",
        "hard_bound": "true",
        "soft_bound": "false"
    }
}