@hostname = http://localhost:5000/api

### test route http://localhost:5000/api/customer/get-test
GET {{hostname}}/customer/get-test

### create new customer

POST {{hostname}}/customer/sign-up
Content-Type: application/json

{
    "full_name": "Yancy Leandro Tupas",
    "email": "YLT@gmail.com",
    "password": "hush",
    "fb_account": "YL.Tupas"
}


### customer log in

POST {{hostname}}/customer/log-in
Content-Type: application/json

{
    "email": "YLT@gmail.com",
    "password": "hush"
}

### customer log out

GET {{hostname}}/customer/log-out

### view customer acc

GET {{hostname}}/customer/my-account
Content-Type: application/json

{
    "user_id": "84000fad-c7ed-4041-8039-0826259a42b6"
}

### update customer

PUT {{hostname}}/customer/update
Content-Type: application/json

{
    "user_id": "90d044e8-b020-47a4-8f7c-9b2d4f3b2a05",
    "phone_number": "333",
    "fb_account": "mc.mc"
}



### create new staff

POST {{hostname}}/owner/new-staff
Content-Type: application/json

{
    "full_name": "Marmalade M. Clementine",
    "phone_number": "7777",
    "email": "wanmoretaym@gmail.com",
    "password": "abcpassword",
    "fb_account": "jam",
    "full_address": "#123, bb. street"
}



### delete staff acc

DELETE {{hostname}}/owner/staff-delete
Content-Type: application/json

{
    "user_id": "90d044e8-b020-47a4-8f7c-9b2d4f3b2a05"
}

### view staff acc

GET {{hostname}}/owner/staff-account
Content-Type: application/json

{
    "user_id": "21d8fd2a-03d0-4574-9c77-d5de79bf729b"
}

### view list of staff list

GET {{hostname}}/owner/staff-list

### upload image for profile picture

POST {{hostname}}/owner/upload-prof-pic
Content-Type: multipart/form-data; boundary=xxxxxx

--xxxxxx

Content-Disposition: form-data; name="prof_pic"; filename="zpermit.png"
Content-Type: image/png

< ./zpermit.png

--xxxxxx--
